## NUMPY

Numpy stands for numerical python.it is a python library.it is a perfect tool for scientific computing and performing array operations and matrics in python

* Arrays
* Arange function
* zeros function, ones function, eye function
* Random values(uniform(0 to 1), normal(-3 to 3)) , random integers(ceil,floor,round)
* indexing and slicing
* colon method.

In [2]:
print(np.__version__)

1.20.1


In [1]:
import numpy as np

In [4]:
A=(1,2,3,4,5,6,7,8,9,10)
print(A)

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)


In [5]:
# Python arrays are used when you need to use many variables which are of the same type.
np.array(A)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.array(A).shape  # single Dimensional array

(10,)

In [7]:
np.array(A).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
B=np.array(A)
print(B)

[ 1  2  3  4  5  6  7  8  9 10]


In [10]:
B.shape

(10,)

In [11]:
B.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

# Builtin Methods

Arange function

Return evenly spaced values within a specified interval

In [16]:
np.arange(1,20) # end point will be n-1 by default equal spacing 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [18]:
np.arange(2,35)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [24]:
np.arange(1,30,3) # 3 is the speceing between the values

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [22]:
np.arange(5,50,5).shape

(9,)

In [21]:
np.arange(5,50,5).reshape(3,3)

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

# zeros function

In [34]:
np.zeros(10) # by default it will give float values

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.zeros(5,dtype='int')

array([0, 0, 0, 0, 0])

In [30]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.zeros((3,3),dtype='int')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [42]:
np.zeros(5)*5

array([0., 0., 0., 0., 0.])

In [98]:
a=np.zeros((3,2),dtype=[('x','float'),('y','int')])
print(a,',',a.ndim)

[[(0., 0) (0., 0)]
 [(0., 0) (0., 0)]
 [(0., 0) (0., 0)]] , 2


In [104]:
np.zeros(3,dtype='int',order='f')

array([0, 0, 0])

# ones function

In [35]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
np.ones(10,dtype='int')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [37]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [39]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [105]:
np.ones((2,2),dtype='int')

array([[1, 1],
       [1, 1]])

### Eye Function

In [3]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [4]:
np.eye(3,dtype='int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [5]:
np.eye(4)*5

array([[5., 0., 0., 0.],
       [0., 5., 0., 0.],
       [0., 0., 5., 0.],
       [0., 0., 0., 5.]])

In [7]:
np.eye(3,3,dtype='int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [8]:
np.eye(3,k=1,dtype='int')

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [9]:
np.eye(3,k=-1,dtype='int')

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0]])

In [11]:
x=np.diag([1,2,3,4,5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


### Random values 

#### rand...uniform distribution..range between 0 to 1

In [12]:
np.random.rand(3)

array([0.34464846, 0.84832082, 0.92931099])

In [13]:
np.random.rand(3,5)

array([[0.0767788 , 0.02688478, 0.58681859, 0.21467927, 0.81053785],
       [0.68610858, 0.68088316, 0.92221617, 0.10190413, 0.73721548],
       [0.48568905, 0.53571815, 0.84586016, 0.36748086, 0.09800925]])

### randn.. normal  distribution..range between -3 to 3

In [14]:
np.random.randn(5)

array([-0.54592878, -1.22115415, -0.2148737 , -0.30391764, -1.10489914])

In [16]:
np.random.randn(4,6)

array([[-0.3955705 ,  0.7706713 ,  0.14439199, -0.13105547, -1.13315811,
         1.13364903],
       [ 0.15820112,  1.27755811,  0.07947868,  0.11381044, -0.12154003,
         1.20240749],
       [ 0.06128835, -0.24381235,  0.44983313,  0.76581638, -0.84772573,
         0.78421885],
       [ 0.26070262,  1.10072443,  0.98025945, -0.57060009,  0.63121995,
        -1.9353765 ]])

### Random integer

In [19]:
np.random.randint(6) ## end point is n-1

5

In [20]:
np.random.randint(3,5) ## one random value is given i.e lies between 3 TO 5

3

In [23]:
np.random.randint(1,15,3) ## 3 random values can be displayed i.e lies between 1to 15

array([10,  3, 14])

In [25]:
np.random.randint(10,20,(2,3))

array([[10, 10, 14],
       [12, 11, 12]])

In [27]:
d=np.arange(1,20)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [31]:
d.shape

(19,)

In [28]:
d.min()

1

In [29]:
d.max()

19

In [32]:
d.argmin() # index position value of minimum

0

In [33]:
d.argmax() # index position of maximum

18

## indexing and slicing

In [34]:
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [35]:
d[4] ## 4 is the index number

5

In [37]:
d[[4,7,9]] ## multiple index numbers

array([ 5,  8, 10])

## colon method

In [39]:
d[1:10] ## end number is n-1, 1 & 10 are index numbers

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
d[2:5]

array([3, 4, 5])

In [42]:
d[2:5]=[100,200,300] ## replacing the values

array([  1,   2, 100, 200, 300,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19])

In [109]:
a=np.arange(5,15)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [110]:
a[2]

7

In [111]:
a[0:1]

array([5])

In [113]:
a[1:3]

array([6, 7])

In [115]:
a[1:3]=[3,4]
a

array([ 5,  3,  4,  8,  9, 10, 11, 12, 13, 14])

### Multdimensional array

In [48]:
a_2d=np.array([[1,5,10],[15,20,25],[30,35,40]])
a_2d

array([[ 1,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [68]:
a_2d.ndim

2

In [49]:
a_2d.shape

(3, 3)

In [50]:
a_2d[1]

array([15, 20, 25])

In [51]:
a_2d[1,2]

25

In [52]:
a_2d[2,1]

35

In [73]:
a_2d[-1]

array([30, 35, 40])

In [74]:
a_2d[-1,0:2]

array([30, 35])

In [53]:
a_2d[[0,1,2],1]

array([ 5, 20, 35])

In [54]:
a_2d[0:3,1:2]

array([[ 5],
       [20],
       [35]])

In [56]:
a_2d[2:3,1:3]

array([[35, 40]])

In [57]:
a_2d[1:2,1:2]

array([[20]])

## comparision

In [58]:
a_2d>15

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [59]:
a_2d[a_2d>15]

array([20, 25, 30, 35, 40])

In [63]:
a_2d[a_2d==40]

array([40])

In [64]:
d

array([  1,   2, 100, 200, 300,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19])

In [69]:
d.ndim

1

## sorting

In [65]:
np.sort(d) # by defalut it takes ascending order

array([  1,   2,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,
        17,  18,  19, 100, 200, 300])

In [67]:
~np.sort(~d)# decending order

array([300, 200, 100,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   2,   1], dtype=int32)

## Transpose 

In [71]:
matrix=np.random.randint(0,20,(3,5))
matrix

array([[ 9,  1, 17,  8,  7],
       [19,  3,  0,  2, 16],
       [18,  9,  4, 12,  9]])

In [72]:
matrix.transpose()

array([[ 9, 19, 18],
       [ 1,  3,  9],
       [17,  0,  4],
       [ 8,  2, 12],
       [ 7, 16,  9]])

In [80]:
matrix.T

array([[ 9, 19, 18],
       [ 1,  3,  9],
       [17,  0,  4],
       [ 8,  2, 12],
       [ 7, 16,  9]])

In [81]:
d

array([  1,   2, 100, 200, 300,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19])

In [82]:
np.append(d,25)   # np.append(variable name,adding value)

array([  1,   2, 100, 200, 300,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  25])

In [83]:
np.insert(d,2,50)   # np.insert(variable name,index position,inserted value)

array([  1,   2,  50, 100, 200, 300,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [84]:
np.delete(d,1)    # np.delete(varible name,index position)

array([  1, 100, 200, 300,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19])

In [90]:
matrix=np.arange(1,16).reshape(3,5)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [92]:
matrix.sum(axis=0) # axis=0 for columns

array([18, 21, 24, 27, 30])

In [93]:
matrix.sum(axis=1) # axis=1 for rows

array([15, 40, 65])

In [94]:
np.delete(matrix,4,axis=1) # np.delete(variable name,index position,axis=o(or)1)

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])

In [95]:
np.delete(matrix,1,axis=0)

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [101]:
a=([[5,10,15]])
b=([[20,25,30]])

In [102]:
np.concatenate((a,b),axis=0)

array([[ 5, 10, 15],
       [20, 25, 30]])

In [103]:
c=np.array([[10,15,20]])
d=np.array([[25,30,35]])

In [104]:
np.concatenate((c,d),axis=0)

array([[10, 15, 20],
       [25, 30, 35]])

In [105]:
np.concatenate((c,d),axis=1)

array([[10, 15, 20, 25, 30, 35]])

In [115]:
a1=np.random.randint(1,5,(2,2))
a2=np.random.randint(1,4,(2,2))
a1

array([[1, 1],
       [4, 2]])

In [116]:
a2

array([[3, 2],
       [1, 2]])

In [117]:
np.add(a1,a2)

array([[4, 3],
       [5, 4]])

In [119]:
np.subtract(a1,a2)

array([[-2, -1],
       [ 3,  0]])

In [120]:
np.multiply(a1,a2) # Normal multiplication

array([[3, 2],
       [4, 4]])

In [121]:
np.matmul(a1,a2) # matrix multiplication

array([[ 4,  4],
       [14, 12]])

In [122]:
a1.dot(a2) # matrix multiplication

array([[ 4,  4],
       [14, 12]])

In [123]:
np.divide(a1,a2)

array([[0.33333333, 0.5       ],
       [4.        , 1.        ]])

In [124]:
np.power(a1,a2)

array([[1, 1],
       [4, 4]], dtype=int32)

In [125]:
np.sqrt(a1)

array([[1.        , 1.        ],
       [2.        , 1.41421356]])

In [126]:
np.sqrt(a2)

array([[1.73205081, 1.41421356],
       [1.        , 1.41421356]])

In [127]:
np.log(a1)

array([[0.        , 0.        ],
       [1.38629436, 0.69314718]])

In [128]:
np.log(a2)

array([[1.09861229, 0.69314718],
       [0.        , 0.69314718]])

## ceil

##roundup the values to the next greatest number

In [137]:
A=np.arange(1,15,1.5)
A

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. , 11.5, 13. , 14.5])

In [138]:
np.ceil(A)

array([ 1.,  3.,  4.,  6.,  7.,  9., 10., 12., 13., 15.])

### Floor

##roundup the values to the least number

In [139]:
np.floor(A)

array([ 1.,  2.,  4.,  5.,  7.,  8., 10., 11., 13., 14.])

## round

In [143]:
B=np.random.rand(5)
B

array([0.70543495, 0.52175073, 0.50883259, 0.87099359, 0.67705856])

In [144]:
np.round(B,3)

array([0.705, 0.522, 0.509, 0.871, 0.677])

## Mean

In [146]:
a1

array([[1, 1],
       [4, 2]])

In [147]:
np.mean(a1)

2.0

In [148]:
np.mean(a1,axis=0) # row average

array([2.5, 1.5])

In [151]:
np.mean(a2,axis=1)  # column average

array([2.5, 1.5])

In [91]:
x=np.array(4)
print(x)
print(x.ndim)

4
0


In [49]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a,',',a.ndim)

[1 2 3 4 5] , 1


In [59]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(b,"no of dimensions=",b.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]] no of dimensions= 2


In [74]:
c=np.array([[[1,1],[2,2]],
           [[3,3],[4,4]]])
print(c.ndim)
c

3


array([[[1, 1],
        [2, 2]],

       [[3, 3],
        [4, 4]]])

In [83]:
d=np.array([[[[1,2,9],[4,5,6]]],
           [[[3,4,7],[5,6,5]]],
           [[[4,8,9],[3,2,6]]]])
print(d.ndim)
d

4


array([[[[1, 2, 9],
         [4, 5, 6]]],


       [[[3, 4, 7],
         [5, 6, 5]]],


       [[[4, 8, 9],
         [3, 2, 6]]]])